### ISSUE TITLE
已失效？

### ISSUE THREAD

**Issue by YodesYang** [imaxct/signer#1]
BDUSS已不再被包含在passport.baidu.com域名下，输入baidu.com下的BDUSS后无法搜索到账户信息。

**Comment by imaxct** [comment]
感谢关注, 这个项目当初完成后就没有一直再维护. 现在可能百度更新了cookie验证算法, 导致获取失败, 接下来有时间我会继续更新, 换成新版APP的接口.

**Comment by YodesYang** [comment]
期待...感谢你的开源精神
